#!/bin/bash /etc/rc.common

USE_PROCD=1
START=99
STOP=10
PIDFILE=/var/run/tempfix_fdb_dsa.pid

start_service() {
    procd_open_instance
    procd_set_param command /root/tempfix_fdb_dsa/tempfix_fdb_dsa.py
    procd_set_param pidfile $PIDFILE
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
        kill $(cat $PIDFILE)
}
